### ISSUE TITLE
Config enable_query_string does not populate fields

### ISSUE THREAD

**Issue by de-raaf-media** [reachweb/statamic-livewire-filters#26]
Although the enable_query_string works for showing the filtered products, they do not seem to populate the checkboxes en text fields in the filters.

Regards,
Mark

**Comment by afonic** [comment]
It should work, I just tried at the demo and it works fine. Can you provide more details ?

**Comment by de-raaf-media** [comment]
Well. I just noticed that te clear filter button appears (and disappears on uncheck). But clicking this button has no effect on the checkbox status eighter. The clear filter does reset the collection so that is odd. I reset the config and views to the default. Everything seems to work except updating the form filed statuses.

I did notice this morning that app.js and app.css return a 404. I included this in the layout file:

`{{ vite src="resources/css/app.css|resources/js/app.js" directory="vendor/statamic-livewire-filters/build" }}`

I honestly don't understand what this should do, which resources directory is used here? I only see an assets directory in vendor/statamic-livewire-filters/build.

**Comment by afonic** [comment]
That's weird are the files in this folder?

Is there any repository I can have access to in order to check this out?

**Comment by de-raaf-media** [comment]
Hey @afonic, I've sent you the files via e-mail.

**Comment by afonic** [comment]
I will check it as well when I have some time and reply here. Usually wire:key shouldn't be needed as these elements don't change after the component is mounted but maybe something with pre-setting the value wasn't working in your example. 

You can probably use the `$value` as the key as it is unique though.

**Comment by de-raaf-media** [comment]
Well in my case the checkboxes with a random key did the trick. But it's not the best solution and won't work for all filters. I agree that $value is unique. But in my case only a random key re-rendered the checkbox it seems.

Thanks for looking into this 👍

**Comment by afonic** [comment]
You forgot to add the "categories" terms in the starter kit but I think I was able to reproduce it anyway.

I will check and let you know!

By the way, the JS and CSS files load for me just fine using the vite tag.

**Comment by afonic** [comment]
OK so the problem is that use Alpine JS in your `resources/js/site.js` file but Livewire loads it again. As soon as I removed the Alpine JS from there and let Livewire load it, it was fixed.

So you have two options:
- You can disable automatically injecting AlpineJS by using the `{{ livewire:scriptConfig }}` tag as you can read here: https://github.com/jonassiewertsen/statamic-livewire?tab=readme-ov-file#livewire-scripts-and-styles
- You can remove Alpine from your `site.js` and let Livewire load it. I suggest you add the `{{ livewire:scripts }}` and `{{ livewire:styles }}` tags in your layout file otherwise the files might not load if a Livewire component is not preset. If you are using the `focus` plugin, Livewire loads all first party plugins by default.
